// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base.proto
// Protobuf Java Version: 4.26.1

package org.base.protos;

public final class BaseProto {
  private BaseProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      BaseProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Order_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_Order_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nbase.proto\022\005proto\"\217\001\n\005Order\022\n\n\002id\030\001 \001(" +
      "\t\022\014\n\004name\030\002 \001(\t\022\031\n\004temp\030\003 \001(\0162\013.proto.Te" +
      "mp\022\021\n\tshelfLife\030\004 \001(\005\022\021\n\tdecayRate\030\005 \001(\001" +
      "\022\022\n\npickupTime\030\006 \001(\003\022\027\n\017orderInsertTime\030" +
      "\007 \001(\003*.\n\004Temp\022\007\n\003any\020\000\022\007\n\003hot\020\001\022\010\n\004cold\020" +
      "\002\022\n\n\006frozen\020\003B\036\n\017org.base.protosB\tBasePr" +
      "otoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_proto_Order_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_Order_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_Order_descriptor,
        new java.lang.String[] { "Id", "Name", "Temp", "ShelfLife", "DecayRate", "PickupTime", "OrderInsertTime", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
