// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base.proto

// Protobuf Java Version: 4.26.1
package org.base.protos;

public interface OrderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.Order)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.proto.Temp temp = 3;</code>
   * @return The enum numeric value on the wire for temp.
   */
  int getTempValue();
  /**
   * <code>.proto.Temp temp = 3;</code>
   * @return The temp.
   */
  org.base.protos.Temp getTemp();

  /**
   * <code>int32 shelfLife = 4;</code>
   * @return The shelfLife.
   */
  int getShelfLife();

  /**
   * <code>double decayRate = 5;</code>
   * @return The decayRate.
   */
  double getDecayRate();

  /**
   * <code>int64 pickupTime = 6;</code>
   * @return The pickupTime.
   */
  long getPickupTime();

  /**
   * <code>int64 orderInsertTime = 7;</code>
   * @return The orderInsertTime.
   */
  long getOrderInsertTime();
}
